package address_mocks

// Streets contains a list of 200 distinct street names in Brazil.
var Streets = []string{
	"Rua Augusta",
	"Avenida Paulista",
	"Rua Oscar Freire",
	"Rua 25 de Março",
	"Avenida Brigadeiro Faria Lima",
	"Rua da Consolação",
	"Avenida Ibirapuera",
	"Rua Teodoro Sampaio",
	"Avenida Rebouças",
	"Rua Vergueiro",
	"Avenida Rio Branco",
	"Avenida Atlântica",
	"Rua do Ouvidor",
	"Rua Visconde de Pirajá",
	"Avenida Copacabana",
	"Rua das Laranjeiras",
	"Avenida Nossa Senhora de Copacabana",
	"Rua Barata Ribeiro",
	"Avenida Epitácio Pessoa",
	"Rua Voluntários da Pátria",
	"Avenida Afonso Pena",
	"Rua da Bahia",
	"Avenida Amazonas",
	"Rua dos Carijós",
	"Avenida do Contorno",
	"Rua Padre Eustáquio",
	"Avenida Cristiano Machado",
	"Rua Curitiba",
	"Avenida Olegário Maciel",
	"Rua Rio Grande do Sul",
	"Avenida Sete de Setembro",
	"Rua Chile",
	"Avenida da França",
	"Rua Carlos Gomes",
	"Avenida Manoel Dias da Silva",
	"Rua Miguel Navarro y Cañizares",
	"Avenida Octávio Mangabeira",
	"Rua da Grécia",
	"Avenida Beira Mar",
	"Rua Monsenhor Tabosa",
	"Avenida Santos Dumont",
	"Rua Barão de Aracati",
	"Avenida Dom Luís",
	"Rua João Cordeiro",
	"Avenida Desembargador Moreira",
	"Rua Osvaldo Cruz",
	"Avenida Washington Soares",
	"Rua Silva Paulet",
	"Avenida Boa Viagem",
	"Rua da Aurora",
	"Avenida Agamenon Magalhães",
	"Rua do Bom Jesus",
	"Avenida Conselheiro Aguiar",
	"Rua Gervásio Pires",
	"Avenida Mascarenhas de Morais",
	"Rua Imperial",
	"Avenida Caxangá",
	"Rua Dom Bosco",
	"Avenida XV de Novembro",
	"Rua das Flores",
	"Avenida Batel",
	"Rua 24 Horas",
	"Avenida Presidente Getúlio Vargas",
	"Rua Saldanha Marinho",
	"Avenida Vicente Machado",
	"Rua XV de Novembro",
	"Avenida Iguaçu",
	"Rua Mateus Leme",
	"Avenida Borges de Medeiros",
	"Rua da Praia",
	"Avenida Carlos Gomes",
	"Rua dos Andradas",
	"Avenida Ipiranga",
	"Rua 24 de Outubro",
	"Avenida Assis Brasil",
	"Rua Mostardeiro",
	"Avenida Goethe",
	"Rua Padre Chagas",
	"Avenida Getúlio Vargas",
	"Rua 10 de Julho",
	"Avenida Eduardo Ribeiro",
	"Rua Barroso",
	"Avenida Djalma Batista",
	"Rua Guilherme Moreira",
	"Avenida André Araújo",
	"Rua Ferreira Pena",
	"Avenida Rodrigo Otávio",
	"Rua Marcílio Dias",
	"Avenida Goiás",
	"Rua 82",
	"Avenida Anhanguera",
	"Rua 90",
	"Avenida T-7",
	"Rua 44",
	"Avenida Portugal",
	"Rua 15",
	"Avenida Mutirão",
	"Rua 10",
	"Avenida Afonso Pena",
	"Rua 14 de Julho",
	"Avenida Mato Grosso",
	"Rua Barão do Rio Branco",
	"Avenida Ricardo Brandão",
	"Rua Antônio Maria Coelho",
	"Avenida Ceará",
	"Rua 25 de Dezembro",
	"Avenida Fernando Corrêa da Costa",
	"Rua Rui Barbosa",
	"Avenida Desembargador Santos Neves",
	"Rua Sete de Setembro",
	"Avenida Beira Mar",
	"Rua da Lama",
	"Avenida Fernando Ferrari",
	"Rua Aleixo Netto",
	"Avenida Saturnino de Brito",
	"Rua João da Silva",
	"Avenida Dante Michelini",
	"Rua Eugênio Netto",
	"Avenida João Pessoa",
	"Rua Duque de Caxias",
	"Avenida Epitácio Pessoa",
	"Rua Maciel Pinheiro",
	"Avenida Rui Barbosa",
	"Rua da Areia",
	"Avenida Dom Pedro I",
	"Rua Rodrigues de Aquino",
	"Avenida Almirante Barroso",
	"Rua General Osório",
	"Avenida Getúlio Vargas",
	"Rua Itabaiana",
	"Avenida Beira Mar",
	"Rua Laranjeiras",
	"Avenida Hermes Fontes",
	"Rua Capela",
	"Avenida Ivo do Prado",
	"Rua Lagarto",
	"Avenida Tancredo Neves",
	"Rua Propriá",
	"Avenida Dom Severino",
	"Rua Coelho Rodrigues",
	"Avenida Frei Serafim",
	"Rua Álvaro Mendes",
	"Avenida Raul Lopes",
	"Rua Paissandu",
	"Avenida Marechal Castelo Branco",
	"Rua Goiás",
	"Avenida Nossa Senhora de Fátima",
	"Rua Climatizada",
	"Avenida Getúlio Vargas",
	"Rua João Pessoa",
	"Avenida Prudente de Morais",
	"Rua Chile",
	"Avenida Salgado Filho",
	"Rua Mossoró",
	"Avenida Roberto Freire",
	"Rua Jaguarari",
	"Avenida Senador Salgado Filho",
	"Rua Apodi",
	"Avenida Presidente Vargas",
	"Rua dos Mundurucus",
	"Avenida Nazaré",
	"Rua Boaventura da Silva",
	"Avenida Almirante Barroso",
	"Rua Ó de Almeida",
	"Avenida Senador Lemos",
	"Rua Gaspar Viana",
	"Avenida Visconde de Souza Franco",
	"Rua Antônio Barreto",
	"Avenida Getúlio Vargas",
	"Rua Tiradentes",
	"Avenida FAB",
	"Rua São José",
	"Avenida Cora de Carvalho",
	"Rua General Rondon",
	"Avenida Coaracy Nunes",
	"Rua Hildemar Maia",
	"Avenida Padre Júlio Maria Lombaerd",
	"Rua Hamilton Silva",
	"Avenida Getúlio Vargas",
	"Rua 104 Sul",
	"Avenida Teotônio Segurado",
	"Rua 106 Sul",
	"Avenida JK",
	"Rua 108 Sul",
	"Avenida LO-02",
	"Rua 110 Sul",
	"Avenida LO-04",
	"Rua 112 Sul",
	"Avenida Brasil",
	"Rua Marechal Deodoro",
	"Avenida Getúlio Vargas",
	"Rua Floriano Peixoto",
	"Avenida Ceará",
	"Rua Alvorada",
	"Avenida Nações Unidas",
	"Rua Rio Grande do Sul",
	"Avenida Epaminondas Jácome",
	"Rua Minas Gerais",
	"Avenida São Paulo",
	"Rua Bahia",
	"Avenida Paraná",
	"Rua Santa Catarina",
	"Avenida Rio de Janeiro",
	"Rua Pernambuco",
	"Avenida Espírito Santo",
	"Rua Goiás",
	"Avenida Maranhão",
	"Rua Piauí",
	"Avenida Ceará",
	"Rua Sergipe",
	"Avenida Alagoas",
	"Rua Paraíba",
	"Avenida Rio Grande do Norte",
	"Rua Tocantins",
	"Avenida Rondônia",
	"Rua Acre",
	"Avenida Amapá",
	"Rua Roraima",
	"Avenida Distrito Federal",
	"Rua Amazonas",
	"Avenida Pará",
	"Rua Mato Grosso",
	"Avenida Mato Grosso do Sul",
	"Rua São Luís",
	"Avenida Teresina",
	"Rua Fortaleza",
	"Avenida Natal",
	"Rua João Pessoa",
	"Avenida Recife",
	"Rua Maceió",
	"Avenida Aracaju",
	"Rua Salvador",
	"Avenida Belo Horizonte",
	"Rua Vitória",
	"Avenida Rio Branco",
	"Rua Porto Velho",
	"Avenida Boa Vista",
	"Rua Macapá",
	"Avenida Palmas",
	"Rua Cuiabá",
	"Avenida Campo Grande",
	"Rua Goiânia",
	"Avenida Brasília",
	"Rua Manaus",
	"Avenida Belém",
	"Rua Curitiba",
	"Avenida Florianópolis",
	"Rua Porto Alegre",
	"Avenida São Paulo",
	"Rua Rio de Janeiro",
	"Avenida Salvador",
	"Rua Recife",
	"Avenida Fortaleza",
	"Rua Belo Horizonte",
	"Avenida Curitiba",
	"Rua Manaus",
	"Avenida Brasília",
	"Rua Goiânia",
	"Avenida Campo Grande",
	"Rua Cuiabá",
	"Avenida Palmas",
	"Rua Macapá",
	"Avenida Boa Vista",
	"Rua Porto Velho",
	"Avenida Rio Branco",
	"Rua Vitória",
	"Avenida Belo Horizonte",
	"Rua Salvador",
	"Avenida Aracaju",
	"Rua Maceió",
	"Avenida Recife",
	"Rua João Pessoa",
	"Avenida Natal",
	"Rua Fortaleza",
	"Avenida Teresina",
	"Rua São Luís",
	"Avenida Mato Grosso do Sul",
	"Rua Mato Grosso",
	"Avenida Pará",
	"Rua Amazonas",
	"Avenida Distrito Federal",
	"Rua Roraima",
	"Avenida Amapá",
	"Rua Acre",
	"Avenida Rondônia",
	"Rua Tocantins",
	"Avenida Rio Grande do Norte",
	"Rua Paraíba",
	"Avenida Alagoas",
	"Rua Sergipe",
	"Avenida Ceará",
	"Rua Piauí",
	"Avenida Maranhão",
	"Rua Goiás",
	"Avenida Espírito Santo",
	"Rua Pernambuco",
	"Avenida Rio de Janeiro",
	"Rua Santa Catarina",
	"Avenida Paraná",
	"Rua Bahia",
	"Avenida São Paulo",
	"Rua Minas Gerais",
}
